plugins {
  id 'java-library'
  id 'maven-publish'
}

group = 'org.discordbots'
version = '3.0.0'
description = 'The community-maintained Java library for Top.gg.'

if (JavaVersion.current() < JavaVersion.VERSION_17) {
  throw new GradleException('Top.gg\'s Java SDK requires Java 17 or later. Java ${JavaVersion.current()} is not supported.')
}

repositories {
  mavenCentral()
}

sourceSets {
  jdaWrapper
  discord4jWrapper

  webhooks
  dropwizardWebhooks
  eclipseJettyWebhooks
  springBootWebhooks
}

configurations {
  dropwizardWebhooksImplementation.extendsFrom(webhooksImplementation)
  eclipseJettyWebhooksImplementation.extendsFrom(webhooksImplementation)
  springBootWebhooksImplementation.extendsFrom(webhooksImplementation)

  googleJavaFormat
}

dependencies {
  implementation 'org.slf4j:slf4j-api:2.0.17'

  implementation 'org.json:json:20251224'
  implementation 'com.squareup.okhttp3:okhttp:5.3.2'
  implementation 'com.google.code.gson:gson:2.13.2'
  implementation 'com.fatboyindustrial.gson-javatime-serialisers:gson-javatime-serialisers:1.1.2'

  jdaWrapperImplementation sourceSets.main.output
  jdaWrapperImplementation 'com.google.code.gson:gson:2.13.2'
  jdaWrapperImplementation('net.dv8tion:JDA:6.3.1') {
    exclude module: 'opus-java'
    exclude module: 'tink' 
  }

  discord4jWrapperImplementation sourceSets.main.output
  discord4jWrapperImplementation 'com.discord4j:discord4j-core:3.3.1'

  webhooksImplementation 'com.google.code.gson:gson:2.13.2'
  webhooksImplementation 'com.fatboyindustrial.gson-javatime-serialisers:gson-javatime-serialisers:1.1.2'

  dropwizardWebhooksImplementation sourceSets.webhooks.output
  dropwizardWebhooksImplementation 'jakarta.ws.rs:jakarta.ws.rs-api:4.0.0'
  dropwizardWebhooksImplementation 'jakarta.servlet:jakarta.servlet-api:6.1.0'

  eclipseJettyWebhooksImplementation sourceSets.webhooks.output
  eclipseJettyWebhooksImplementation 'jakarta.servlet:jakarta.servlet-api:6.1.0'

  springBootWebhooksImplementation sourceSets.webhooks.output
  springBootWebhooksImplementation 'org.springframework.boot:spring-boot-starter-web:4.0.3'
  springBootWebhooksImplementation 'jakarta.servlet:jakarta.servlet-api:6.1.0'

  googleJavaFormat 'com.google.googlejavaformat:google-java-format:1.34.1'
}

tasks.register('format', JavaExec) {
  group = 'format'
  description = 'Format code'
  classpath = configurations.googleJavaFormat
  mainClass = 'com.google.googlejavaformat.java.Main'

  def sources = fileTree(dir: 'src', include: '**/*.java')
  args = ['-i'] + sources

  inputs.files(sources)
  outputs.files(sources)

  jvmArgs(
    '--add-exports=jdk.compiler/com.sun.tools.javac.api=ALL-UNNAMED',
    '--add-exports=jdk.compiler/com.sun.tools.javac.code=ALL-UNNAMED',
    '--add-exports=jdk.compiler/com.sun.tools.javac.file=ALL-UNNAMED',
    '--add-exports=jdk.compiler/com.sun.tools.javac.parser=ALL-UNNAMED',
    '--add-exports=jdk.compiler/com.sun.tools.javac.tree=ALL-UNNAMED',
    '--add-exports=jdk.compiler/com.sun.tools.javac.util=ALL-UNNAMED'
  )
}

tasks.withType(JavaCompile) {
  options.compilerArgs << '-Xlint:deprecation'
}