plugins {
  id 'java-library'
  id 'maven-publish'
}

def ver = '1.0.0'

group = 'gg.top'
version = ver
description = 'The community-maintained Java SDK for Top.gg.'

if (JavaVersion.current() < JavaVersion.VERSION_17) {
  throw new GradleException("Top.gg\'s Java SDK requires Java 17 or later. Java ${JavaVersion.current()} is not supported.")
}

repositories {
  mavenCentral()
}

sourceSets {
  jdaWrapper
  discord4jWrapper

  webhooks
  dropwizardWebhooks
  eclipseJettyWebhooks
  springBootWebhooks
}

configurations {
  dropwizardWebhooksImplementation.extendsFrom webhooksImplementation
  eclipseJettyWebhooksImplementation.extendsFrom webhooksImplementation
  springBootWebhooksImplementation.extendsFrom webhooksImplementation

  testImplementation.extendsFrom dropwizardWebhooksImplementation
  testImplementation.extendsFrom eclipseJettyWebhooksImplementation
  testImplementation.extendsFrom springBootWebhooksImplementation

  googleJavaFormat
}

test {
  useJUnitPlatform()
}

java {
  withJavadocJar()
  withSourcesJar()

  registerFeature('jdaWrapper') {
    usingSourceSet sourceSets.jdaWrapper
    
    capability('gg.top', 'jdaWrapper', ver)
  }

  registerFeature('discord4jWrapper') {
    usingSourceSet sourceSets.discord4jWrapper
    
    capability('gg.top', 'discord4jWrapper', ver)
  }

  registerFeature('webhooks') {
    usingSourceSet sourceSets.webhooks
    
    capability('gg.top', 'webhooks', ver)
  }

  registerFeature('dropwizardWebhooks') {
    usingSourceSet sourceSets.webhooks
    usingSourceSet sourceSets.dropwizardWebhooks

    capability('gg.top', 'dropwizardWebhooks', ver)
  }

  registerFeature('eclipseJettyWebhooks') {
    usingSourceSet sourceSets.webhooks
    usingSourceSet sourceSets.eclipseJettyWebhooks

    capability('gg.top', 'eclipseJettyWebhooks', ver)
  }

  registerFeature('springBootWebhooks') {
    usingSourceSet sourceSets.webhooks
    usingSourceSet sourceSets.springBootWebhooks

    capability('gg.top', 'springBootWebhooks', ver)
  }

  javadoc {
    title = '<h1>Top.gg Java SDK</h1>'

    options.bottom = '<i>Copyright &#169; 2018-2026 Top.gg. All Rights Reserved.</i>'
    options.encoding = 'UTF-8'
    options.docEncoding = 'UTF-8'
    options.charSet = 'UTF-8'
    options.addBooleanOption('html5', true)

    source += sourceSets.jdaWrapper.allJava
    source += sourceSets.discord4jWrapper.allJava
    source += sourceSets.dropwizardWebhooks.allJava
    source += sourceSets.eclipseJettyWebhooks.allJava
    source += sourceSets.springBootWebhooks.allJava
    source += sourceSets.webhooks.allJava

    classpath += sourceSets.jdaWrapper.compileClasspath
    classpath += sourceSets.discord4jWrapper.compileClasspath
    classpath += sourceSets.dropwizardWebhooks.compileClasspath
    classpath += sourceSets.eclipseJettyWebhooks.compileClasspath
    classpath += sourceSets.springBootWebhooks.compileClasspath
    classpath += sourceSets.webhooks.compileClasspath
  }
}

publishing {
  publications {
    maven(MavenPublication) {
      artifactId = 'SDK'
      groupId = 'gg.top'
      version = ver
    
      from components.java
      
      pom {
        name = 'SDK'
        description = 'The community-maintained Java SDK for Top.gg.'
        url = 'https://github.com/top-gg-community/java-sdk'
        inceptionYear = '2018'
        
        licenses {
          license {
            name = 'Apache License 2.0'
            distribution = 'repo'
            url = "https://github.com/top-gg-community/java-sdk/blob/$ver/LICENSE"
          }
        }
        
        developers {
          developer {
            id = 'top-gg-community'
            name = 'Top.gg'
            url = 'https://github.com/top-gg-community'
          }
        }
        
        scm {
          url = 'https://github.com/top-gg-community/java-sdk'
          connection = 'scm:git:github.com/top-gg-community/java-sdk.git'
          developerConnection = 'scm:git:ssh://github.com/top-gg-community/java-sdk.git'
        }
        
        issueManagement {
          system = 'GitHub'
          url = 'https://github.com/top-gg-community/java-sdk/issues'
        }
        
        ciManagement {
          system = 'Github Actions'
          url = 'https://github.com/top-gg-community/java-sdk/actions'
        }
      }
    }
  }
  
  repositories {
    maven {
      url = layout.buildDirectory.dir 'staging-deploy'
    }
  }
}

dependencies {
  implementation 'org.slf4j:slf4j-api:2.0.17'

  implementation 'org.json:json:20251224'
  api 'com.squareup.okhttp3:okhttp:5.3.2'
  implementation 'com.google.code.gson:gson:2.13.2'
  implementation 'com.fatboyindustrial.gson-javatime-serialisers:gson-javatime-serialisers:1.1.2'

  jdaWrapperImplementation sourceSets.main.output
  jdaWrapperImplementation 'com.google.code.gson:gson:2.13.2'
  jdaWrapperApi('net.dv8tion:JDA:6.3.1') {
    exclude module: 'opus-java'
    exclude module: 'tink' 
  }

  discord4jWrapperImplementation sourceSets.main.output
  discord4jWrapperApi 'com.discord4j:discord4j-core:3.3.1'

  webhooksImplementation 'com.google.code.gson:gson:2.13.2'
  webhooksImplementation 'com.fatboyindustrial.gson-javatime-serialisers:gson-javatime-serialisers:1.1.2'

  dropwizardWebhooksImplementation sourceSets.webhooks.output
  dropwizardWebhooksImplementation 'jakarta.ws.rs:jakarta.ws.rs-api:4.0.0'
  dropwizardWebhooksImplementation 'jakarta.servlet:jakarta.servlet-api:6.1.0'
  dropwizardWebhooksImplementation 'com.google.guava:guava:33.5.0-jre'

  eclipseJettyWebhooksImplementation sourceSets.webhooks.output
  eclipseJettyWebhooksApi 'jakarta.servlet:jakarta.servlet-api:6.1.0'
  eclipseJettyWebhooksImplementation 'com.google.guava:guava:33.5.0-jre'

  springBootWebhooksImplementation sourceSets.webhooks.output
  springBootWebhooksImplementation 'org.springframework.boot:spring-boot-starter-web:4.0.3'
  springBootWebhooksImplementation 'jakarta.servlet:jakarta.servlet-api:6.1.0'

  testImplementation 'org.junit.jupiter:junit-jupiter-api:6.0.3'
  testImplementation 'org.junit.platform:junit-platform-suite-api:6.0.3'
  testImplementation 'com.google.code.gson:gson:2.13.2'
  testImplementation 'io.dropwizard:dropwizard-testing:5.0.1'
  testImplementation 'org.springframework.boot:spring-boot-starter-test-classic:4.0.3'
  testImplementation 'org.springframework.boot:spring-boot-starter-security-test:4.0.3'

  testImplementation sourceSets.dropwizardWebhooks.output
  testImplementation sourceSets.eclipseJettyWebhooks.output
  testImplementation sourceSets.springBootWebhooks.output

  testCompileOnly 'org.junit.jupiter:junit-jupiter-params:6.0.3'
  testRuntimeOnly 'org.junit.jupiter:junit-jupiter-engine:6.0.3'
  testRuntimeOnly 'org.junit.platform:junit-platform-launcher:6.0.3'

  googleJavaFormat 'com.google.googlejavaformat:google-java-format:1.34.1'
}

tasks.register('format', JavaExec) {
  group = 'format'
  description = 'Format code'
  classpath = configurations.googleJavaFormat
  mainClass = 'com.google.googlejavaformat.java.Main'

  def sources = fileTree(dir: 'src', include: '**/*.java')
  args = ['-i'] + sources

  inputs.files sources
  outputs.files sources

  jvmArgs(
    '--add-exports=jdk.compiler/com.sun.tools.javac.api=ALL-UNNAMED',
    '--add-exports=jdk.compiler/com.sun.tools.javac.code=ALL-UNNAMED',
    '--add-exports=jdk.compiler/com.sun.tools.javac.file=ALL-UNNAMED',
    '--add-exports=jdk.compiler/com.sun.tools.javac.parser=ALL-UNNAMED',
    '--add-exports=jdk.compiler/com.sun.tools.javac.tree=ALL-UNNAMED',
    '--add-exports=jdk.compiler/com.sun.tools.javac.util=ALL-UNNAMED'
  )
}

tasks.withType(JavaCompile) {
  options.compilerArgs << '-Xlint:deprecation'
}

tasks.withType(Javadoc) {
  options.memberLevel = JavadocMemberLevel.PUBLIC
}